# Generated by Django 3.0.7 on 2020-06-06 19:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awewards', '0002_auto_20200606_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='owner',
            new_name='uploader',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_link',
        ),
        migrations.AddField(
            model_name='projects',
            name='github_repo',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='profpics'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='projectpics/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='url',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
